config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('pages.urls')),
    path('crm/', include('crm.urls')),
    path('users/', include('users.urls')),

]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ContactList.as_view(), name="contact_list"),
    path("contacts/", views.ContactList.as_view(), name = "contact_list"),
    path("contacts/lastcontacted", views.ContactsNeedUpdate.as_view(), name = "contact_lastcontacted"),
    path("contacts/contactbycompany", views.ContactsByCompany.as_view(), name = "contact_bycompany"),
    path("contacts/<int:pk>/", views.ContactDetail.as_view(), name = "contactdetail"),
    path("contacts/<int:pk>/edit", views.ContactEdit.as_view(), name = "contactedit"),
    path("contacts/<int:pk>/delete", views.ContactDelete.as_view(), name = "contact_delete"),
    path("contacts/new", views.ContactCreate.as_view(), name = "contact_new"),

    path("company/", views.CompanyList.as_view(), name = "company_list"),
    path("company/industry", views.CompanyByIndustry.as_view(), name = "company_byindustry"),
    path("company/<int:pk>/", views.CompanyDetail.as_view(), name = "companydetail"),
    path("company/<int:pk>/edit", views.CompanyEdit.as_view(), name = "companyedit"),
    path("company/<int:pk>/delete", views.CompanyDelete.as_view(), name = "company_delete"),
    path("company/new", views.CompanyCreate.as_view(), name = "company_new"),

    path("deals/", views.DealList.as_view(), name = "deal_list"),
    path("deals/<int:pk>/", views.DealDetails.as_view(), name = "dealdetail"),
    path("deals/<int:pk>/edit", views.DealEdit.as_view(), name = "dealedit"),
    path("deals/<int:pk>/delete", views.DealDelete.as_view(), name = "deal_delete"),
    path("deals/new", views.DealCreate.as_view(), name = "deal_new"),
    path("deals/closedate", views.DealbyCloseDate.as_view(), name = "deal_byclosedate"),
    path("deals/status", views.DealbyStatus.as_view(), name = "deal_bystatus"),

]

crm/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=100)
    industry = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    notes = models.TextField()
    addressLineOne = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    stateProv = models.CharField(max_length=50, blank=True, null=True)
    zipcode = models.CharField(max_length=20, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("companydetail", args=[self.id])

class Contact(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    phone = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(unique=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    birthday = models.DateField(auto_now=False, auto_now_add=False)
    lastcontactdate = models.DateField(auto_now=False, auto_now_add=False)
    notes = models.TextField()
    addressLineOne = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    stateProv = models.CharField(max_length=50, blank=True, null=True)
    zipcode = models.CharField(max_length=20, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return (f"{self.firstname} {self.lastname}")
    
    def get_absolute_url(self):
        return reverse("contactdetail", args=[self.id])

class Deal(models.Model):
    status_choices = [
        ('opportunity', '1-Opportunity'),
        ('qualification', '2-Qualification'),
        ('negotiation', '3-Negotiation'),
        ('closed', 'Closed (Won)'),
        ('Lost', 'Closed (Lost)'),

    ]
    title = models.CharField(max_length=200)
    expectedclosedate = models.DateField(auto_now=False, auto_now_add=False)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    notes = models.TextField()
    status = models.CharField(max_length=20, choices=status_choices, default='opportunity')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("dealdetail", args=[self.id])

crm/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import Company, Contact, Deal
from django.urls import reverse_lazy
from django import forms

# Create your views here.

# Contact Views 

class ContactList(ListView):
    template_name = "crm/contactlist.html"
    model = Contact

    def get_queryset(self):
        logged_user = self.request.user
        return Contact.objects.filter(author = logged_user)
    
class ContactsNeedUpdate(ListView):
    template_name = "crm/contactupdated.html"
        
    def get_queryset(self):
        logged_user = self.request.user
        return Contact.objects.filter(author = logged_user).order_by('-lastcontactdate')
    model = Contact

class ContactsByCompany(ListView):
    template_name = "crm/contactupdated.html" 
    model = Contact

    def get_queryset(self):
        logged_user = self.request.user
        return Contact.objects.filter(author = logged_user).order_by('company')


class ContactDetail(DetailView):
    template_name = "crm/contactdetails.html"
    model = Contact

    def get_queryset(self):
        logged_user = self.request.user
        return Contact.objects.filter(author = logged_user)


class ContactCreate(CreateView):
    template_name = "crm/contactnew.html"
    model = Contact
    fields = [ 
        "firstname", "lastname", "phone", "email", "company", "birthday", "lastcontactdate", "notes", "addressLineOne", "city", "stateProv", "zipcode"
    ]
    def form_valid(self, form):
        # before saving the record
        # set the author to be the logged in user
        form.instance.author = self.request.user
        return super().form_valid(form)

class ContactEdit(UpdateView):
    template_name = "crm/contactedit.html"
    model = Contact
    fields = [ 
        "firstname", "lastname", "phone", "email", "company", "birthday", "lastcontactdate", "notes", "addressLineOne", "city", "stateProv", "zipcode"
    ]


class ContactDelete(DeleteView):
    template_name = "crm/contactdelete.html"
    model = Contact
    success_url = reverse_lazy("contact_list")


#Company Views


class CompanyList(ListView):
    template_name = "crm/companylist.html"
    model = Company

    def get_queryset(self):
        logged_user = self.request.user
        return Company.objects.filter(author = logged_user)

class CompanyDetail(DetailView):
    template_name = "crm/companydetails.html"
    model = Company

class CompanyByIndustry(ListView):
    template_name = "crm/companyindustry.html"
    model = Company
    
    def get_queryset(self):
        logged_user = self.request.user
        return Company.objects.filter(author = logged_user).order_by('industry')
  

class CompanyCreate(CreateView):
    template_name = "crm/companynew.html"
    model = Company
    fields = [ 
        "name", "industry", "phone", "notes", "addressLineOne", "city", "stateProv", "zipcode"
    ]

    def form_valid(self, form):
        # before saving the record
        # set the author to be the logged in user
        form.instance.author = self.request.user
        return super().form_valid(form)

class CompanyEdit(UpdateView):
    template_name = "crm/companyedit.html"
    model = Company
    fields = [ 
        "name", "industry", "phone", "notes", "addressLineOne", "city", "stateProv", "zipcode"
    ]

class CompanyDelete(DeleteView):
    template_name = "crm/companydelete.html"
    model = Company
    success_url = reverse_lazy("company_list")



# Deal Views


class DealList(ListView):
    template_name = "crm/deallist.html"
    model = Deal

    def get_queryset(self):
        logged_user = self.request.user
        return Deal.objects.filter(author = logged_user)

class DealDetails(DetailView):
    template_name = "crm/dealdetails.html"
    model = Deal

class DealCreate(CreateView):
    template_name = "crm/dealnew.html"
    model = Deal
    fields = [
        "title", "expectedclosedate", "amount", "company", "notes", "status"
    ]

    def form_valid(self, form):
        # before saving the record
        # set the author to be the logged in user
        form.instance.author = self.request.user
        return super().form_valid(form)


class DealEdit(UpdateView):
    template_name = "crm/dealedit.html"
    model = Deal
    fields = [
        "title", "expectedclosedate", "amount", "company", "notes", "status"
    ]

class DealDelete(DeleteView):
    template_name = "crm/dealdelete.html"
    model = Deal

class DealbyStatus(ListView):
    template_name = "crm/dealbystatus.html"
    model = Deal
    def get_queryset(self):
        logged_user = self.request.user
        return Deal.objects.filter(author = logged_user).order_by('status')


class DealbyCloseDate(ListView):
    template_name = "crm/dealbyclosedate.html"
    model = Deal
    
    def get_queryset(self):
        logged_user = self.request.user
        return Deal.objects.filter(author = logged_user).order_by('-expectedclosedate')
   

templates/crm/companydelete.html
{% extends 'base.html' %}

{% block title %} Delete Company {% endblock title %}

{% block content %}
<h1> Delete Contact </h1>
<p> Are you sure you're like to delete {{company.name}} ?</p>

<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="confirm">
</form>

{% endblock content %}

templates/crm/companydetails.html
{% extends 'base.html' %}

{% block title} {{contact.firstname}} {{contact.lastname}} {% endblock title}

{% block content %}

{% include 'crm/companynavbar.html' %}

<div class="container">

  <div class="row">
    <div class="col-4"> Name  </div>
    <div class="col-8"> {{company.name}}  </div>
    <div class="col-4"> Industry  </div>
    <div class="col-8"> {{company.industry}} </div>
    <div class="col-4"> Phone  </div>
    <div class="col-8"> {{company.phone}}  </div>
    <div class="col-4"> Address  </div>
    <div class="col-8"> {{company.addressLineOne}} <br> {{company.city}} <br> {{company.stateProv}} <br> {{company.zipcode}} </div>
    <div class="col-4"> Notes  </div>
    <div class="col-8"> {{company.notes}} </div>


  </div>
</div>




    <br> <br> <br>

    <a href="{% url 'companyedit' company.id %}" class="btn btn-warning"> Edit Company</a>


 


{% endblock content %}

templates/crm/companyedit.html
{% extends 'base.html' %}

{% block title %} Edit Company {% endblock title %}

{% block content %}

{% include 'crm/companynavbar.html' %}

<h1> New Contact</h1>
<form method="POST">
    {% csrf_token %}
<div class="container">

  <div class="row">
    <div class="col-4"> Name </div>
    <div class="col-8"> {{form.name}}</div>
    <div class="col-4"> Industry  </div>
    <div class="col-8"> {{form.industry}} </div>
    <div class="col-4"> Phone  </div>
    <div class="col-8"> {{form.phone}}  </div>
    <div class="col-4"> Address  </div>
    <div class="col-8"> {{form.addressLineOne}} </div>
    <div class="col-4"> City</div>
    <div class="col-8"> {{form.city}} </div>
    <div class="col-4"> State </div>
    <div class="col-8"> {{form.stateProv}} </div>
    <div class="col-4"> Zip Code </div>
    <div class="col-8"> {{form.zipcode}} </div>
    <div class="col-4"> Notes  </div>
    <div class="col-8"> {{form.notes}} </div>


  </div>
</div>



    <input type="submit" class="btn btn-success" value="Save">
</form>

<br> <br>

 <a href="{% url 'company_delete' company.id %}" class="btn btn-danger"> Delete Company</a>


{% endblock content %}

templates/crm/companynew.html
{% extends 'base.html' %}

{% block title %} New Company {% endblock title %}

{% block content %}

{% include 'crm/companynavbar.html' %}

<h1> New Contact </h1>
<form method="POST">
    {% csrf_token %}
<div class="container">

  <div class="row">
    <div class="col-4"> Name </div>
    <div class="col-8"> {{form.name}}</div>
    <div class="col-4"> Industry  </div>
    <div class="col-8"> {{form.industry}} </div>
    <div class="col-4"> Phone  </div>
    <div class="col-8"> {{form.phone}}  </div>
    <div class="col-4"> Address  </div>
    <div class="col-8"> {{form.addressLineOne}} </div>
    <div class="col-4"> City</div>
    <div class="col-8"> {{form.city}} </div>
    <div class="col-4"> State </div>
    <div class="col-8"> {{form.stateProv}} </div>
    <div class="col-4"> Zip Code </div>
    <div class="col-8"> {{form.zipcode}} </div>
    <div class="col-4"> Notes  </div>
    <div class="col-8"> {{form.notes}} </div>


  </div>
</div>



    <input type="submit" class="btn btn-success" value="create">
</form>

{% endblock content %}

templates/crm/contactbycompany.html
{% extends 'base.html' %}

{% block title %} Contact List {% endblock title %}

{% block content %}

{% include 'crm/contactnavbar.html' %}



<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">See Details</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name </th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">Company</th>

    </tr>
  </thead>
  <tbody>
    {% for contact in contact_list %}
    <tr>
      <td>{{contact.id}}</td>
      <td><a href=" {% url 'contactdetail' contact.id %}" class="btn btn-primary"> Details </a></td>
      <td>{{contact.firstname}}</td>
      <td>{{contact.lastname}}</td>
      <td>{{contact.phone}}</td>
      <td>{{contact.email}}</td>
      <td>{{contact.company}}</td>
    </tr>
    {% endfor %}

    
  </tbody>
</table>
   
{% endblock content %}

templates/crm/contactdelete.html
{% extends 'base.html' %}

{% block title %} Delete Contact {% endblock title %}

{% block content %}
<h1> Delete Contact </h1>
<p> Are you sure you're like to delete : {{contact.firstname}} {{contact.lastname}} ?</p>

<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="confirm">
</form>

{% endblock content %}

templates/crm/contactdetails.html
{% extends 'base.html' %}

{% block title} {{contact.firstname}} {{contact.lastname}} {% endblock title}

{% block content %}

{% include 'crm/contactnavbar.html' %}

<div class="container">
    <a href="mailto:{{contact.email}}" class="btn btn-primary"> Open Email App </a>
    <a href="tel:{{contact.phone}}" class="btn btn-info"> Call Contact </a>
    <br><br>

  <div class="row">
    <div class="col-4"> Name  </div>
    <div class="col-8"> {{contact.firstname}} {{contact.lastname}}  </div>
    <div class="col-4"> Email  </div>
    <div class="col-8"> {{contact.email}} </div>
    <div class="col-4"> Phone  </div>
    <div class="col-8"> {{contact.phone}}  </div>
    <div class="col-4"> Company  </div>
    <div class="col-8"> {{contact.company}}  </div>
    <div class="col-4"> Birthday  </div>
    <div class="col-8"> {{contact.birthday}} </div>
    <div class="col-4"> Last Contacted Date  </div>
    <div class="col-8"> {{contact.lastcontactdate}} </div>
    <div class="col-4"> Address  </div>
    <div class="col-8"> {{contact.addressLineOne}} <br> {{contact.city}} <br> {{contact.stateProv}} <br> {{contact.zipcode}} </div>
    <div class="col-4"> Notes  </div>
    <div class="col-8"> {{contact.notes}} </div>


  </div>
</div>




    <br> <br> <br>

    <a href="{% url 'contactedit' contact.id %}" class="btn btn-warning"> Edit Contact</a>


    <div class="container mt-5">
        <h2>Compose Email </h2>
        <form id="emailForm">
            {% csrf_token %}
            <div class="mb-3">
                <label for="recipient" class="form-label">Recipient Email</label>
                <input type="email" class="form-control" id="recipient" name="recipient" value="{{contact.email}}" required>
            </div>
            <div class="mb-3">
                <label for="subject" class="form-label">Subject</label>
                <input type="text" class="form-control" id="subject" name="subject">
            </div>
            <div class="mb-3">
                <label for="body" class="form-label">Body</label>
                <textarea class="form-control" id="body" name="body" rows="5"></textarea>
            </div>
            <button type="button" class="btn btn-primary" onclick="generateMailto()">Generate Email Link</button>
        </form>
        <div class="mt-3">
            <a id="mailtoLink" href="#" class="btn btn-success" style="display: none;">Open Email</a>
        </div>
    </div>

    <script>
        function generateMailto() {
            // Get form values
            const recipient = document.getElementById('recipient').value;
            const subject = encodeURIComponent(document.getElementById('subject').value);
            const body = encodeURIComponent(document.getElementById('body').value);

            // Construct mailto link
            const mailto = `mailto:${recipient}?subject=${subject}&body=${body}`;
            
            // Update the link
            const mailtoLink = document.getElementById('mailtoLink');
            mailtoLink.href = mailto;
            mailtoLink.style.display = 'inline-block';
            mailtoLink.textContent = `Send Email to ${recipient}`;
        }
    </script>


{% endblock content %}

templates/crm/contactedit.html
{% extends 'base.html' %}

{% block title %} Contact List {% endblock title %}

{% block content %}

{% include 'crm/contactnavbar.html' %}

<h1> New Contact</h1>
<form method="POST">
    {% csrf_token %}
<div class="container">

  <div class="row">
    <div class="col-4"> Name (First / Last) </div>
    <div class="col-8"> {{form.firstname}} {{form.lastname}}  </div>
    <div class="col-4"> Email  </div>
    <div class="col-8"> {{form.email}} </div>
    <div class="col-4"> Phone  </div>
    <div class="col-8"> {{form.phone}}  </div>
    <div class="col-4"> Company  </div>
    <div class="col-8"> {{form.company}}  </div>
    <div class="col-4"> Birthday  </div>
    <div class="col-8"> <input type="date" name="birthday" id="id_birthday" value="{{contact.birthday|date:'Y-m-d'}}" required> </div>
    <div class="col-4"> Last Contacted Date  </div>
    <div class="col-8"> <input type="date" name = "lastcontactdate" id= "id_lastcontactdate" value="{{contact.lastcontactdate|date:'Y-m-d'}}" > </div>
    <div class="col-4"> Address  </div>
    <div class="col-8"> {{form.addressLineOne}} </div>
    <div class="col-4"> City</div>
    <div class="col-8"> {{form.city}} </div>
    <div class="col-4"> State </div>
    <div class="col-8"> {{form.stateProv}} </div>
    <div class="col-4"> Zip Code </div>
    <div class="col-8"> {{form.zipcode}} </div>
    <div class="col-4"> Notes  </div>
    <div class="col-8"> {{form.notes}} </div>


  </div>
</div>



    <input type="submit" class="btn btn-success" value="Save">
</form>

<br> <br>

 <a href="{% url 'contact_delete' contact.id %}" class="btn btn-danger"> Delete Contact</a>


{% endblock content %}

templates/crm/contactlist.html
{% extends 'base.html' %}

{% block title %} Contact List {% endblock title %}

{% block content %}

{% include 'crm/contactnavbar.html' %}



<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">See Details</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name </th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">Company</th>

    </tr>
  </thead>
  <tbody>
    {% for contact in contact_list %}
    <tr>
      <td>{{contact.id}}</td>
      <td><a href=" {% url 'contactdetail' contact.id %}" class="btn btn-primary"> Details </a></td>
      <td>{{contact.firstname}}</td>
      <td>{{contact.lastname}}</td>
      <td>{{contact.phone}}</td>
      <td>{{contact.email}}</td>
      <td>{{contact.company}}</td>
    </tr>
    {% endfor %}

    
  </tbody>
</table>
   
{% endblock content %}

templates/crm/contactupdated.html
{% extends 'base.html' %}

{% block title %} Contact List {% endblock title %}

{% block content %}

{% include 'crm/contactnavbar.html' %}



<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">See Details</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name </th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">Company</th>
      <th scope="col">Last Contacted Date</th>

    </tr>
  </thead>
  <tbody>
    {% for contact in contact_list %}
    <tr>
      <td>{{contact.id}}</td>
      <td><a href=" {% url 'contactdetail' contact.id %}" class="btn btn-primary"> Details </a></td>
      <td>{{contact.firstname}}</td>
      <td>{{contact.lastname}}</td>
      <td>{{contact.phone}}</td>
      <td>{{contact.email}}</td>
      <td>{{contact.company}}</td>
      <td>{{contact.lastcontactdate}}</td>
    </tr>
    {% endfor %}

    
  </tbody>
</table>
   
{% endblock content %}

templates/crm/dealbystatus.html
{% extends 'base.html' %}

{% block title %} My Deals {% endblock title %}

{% block content %}

{% include 'crm/dealnavbar.html' %}




<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">See Details</th>
      <th scope="col">Title</th>
      <th scope="col">Amount </th>
      <th scope="col">Company</th>
      <th scope="col">Status</th>


    </tr>
  </thead>
  <tbody>
    {% for deal in deal_list %}
    <tr>
      <th scope="row">{{deal.id}}</th>
      <td><a href=" {% url 'dealdetail' deal.id %}" class="btn btn-primary"> Details </a></td>
      <td>{{deal.title}}</td>
      <td>{{deal.amount}}</td>
      <td>{{deal.company}}</td>
      <td>{{deal.status}}</td>
    </tr>
    {% endfor %}

    
  </tbody>
</table>
   
{% endblock content %}

templates/crm/dealdelete.html
{% extends 'base.html' %}

{% block title %} Delete Deal {% endblock title %}

{% block content %}
<h1> Delete Contact </h1>
<p> Are you sure you're like to delete {{deal.title}} ?</p>

<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="confirm">
</form>

{% endblock content %}

templates/crm/dealdetails.html
{% extends 'base.html' %}

{% block title} {{deal.title}} {% endblock title}

{% block content %}

{% include 'crm/dealnavbar.html' %}

<div class="container">

  <div class="row">
    <div class="col-4"> Title  </div>
    <div class="col-8"> {{deal.title}}  </div>
    <div class="col-4"> Expected close date  </div>
    <div class="col-8"> {{deal.expectedclosedate}}</div>
    <div class="col-4"> Amount ($)  </div>
    <div class="col-8"> {{deal.amount}} </div>
    <div class="col-4"> Company  </div>
    <div class="col-8"> {{deal.company}} </div>
    <div class="col-4"> Notes  </div>
    <div class="col-8"> {{deal.notes}} </div>
    <div class="col-4"> Status  </div>
    <div class="col-8"> {{deal.status}} </div>


  </div>
</div>




    <br> <br> <br>

    <a href="{% url 'dealedit' deal.id %}" class="btn btn-warning"> Edit Deal</a>


 


{% endblock content %}

templates/crm/dealnew.html
{% extends 'base.html' %}

{% block title %} New Deal {% endblock title %}

{% block content %}

{% include 'crm/dealnavbar.html' %}

<h1> New Deal </h1>
<form method="POST">
    {% csrf_token %}
<div class="container">

  <div class="row">
    <div class="col-4"> Title </div>
    <div class="col-8"> {{form.title}}</div>
    <div class="col-4"> Expected Close Date  </div>
    <div class="col-8"> <input type="date" name="expectedclosedate" id="id_expectedclosedate" required> </div>
    <div class="col-4"> Amount ($) </div>
    <div class="col-8"> {{form.amount}}  </div>
    <div class="col-4"> Company  </div>
    <div class="col-8"> {{form.company}} </div>
    <div class="col-4"> Notes</div>
    <div class="col-8"> {{form.notes}} </div>
    <div class="col-4"> Status </div>
    <div class="col-8"> {{form.status}} </div>



  </div>
</div>



    <input type="submit" class="btn btn-success" value="create">
</form>

{% endblock content %}